# -*- coding: utf-8 -*-
"""Count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnHKD0uRD_w_xUoaZ-7K1mGW2Gd25YOJ
"""

# Import required libraries 
import cv2 
import numpy as np 
import dlib



# Detect the coordinates 
detector = dlib.get_frontal_face_detector()

def face_counter(path):
  gray = cv2.cvtColor(path, cv2.COLOR_BGR2GRAY) 
  faces = detector(gray) 
  
    # Iterator to count faces 
  i = 0
  for face in faces: 
  
  # Get the coordinates of faces 
    x, y = face.left(), face.top() 
    x1, y1 = face.right(), face.bottom() 
    cv2.rectangle(path, (x, y), (x1, y1), (0, 255, 0), 2) 
  
  # Increment iterator for each face in faces 
    i = i+1
  
  # Display the box and faces 
    cv2.putText(path, 'face num'+str(i), (x-10, y-10), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2) 
    print(face, i)
    print(i)
    from google.colab.patches import cv2_imshow 
    # Display the resulting frame 
  cv2_imshow(path) 
  
  
# Release the capture and destroy the windows  
cv2.destroyAllWindows()

